pmvc/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'pmvc'

urlpatterns = [
    path('', views.index, name='index'),
    path('account_home', views.AccountHome, name='AccountHome'),
    path('account_selection_handler', views.AccountSelectionHandler, name='AccountSelectionHandler'),
    path('account_selected/<int:account_id>', views.AccountSelected, name='AccountSelected'),
    path('list_videos/<int:account_id>', views.ListVideos, name='ListVideos'),
    path('ingest_video/<int:account_id>', views.IngestVideo, name='IngestVideo'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shastarain/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('pmvc/', include('pmvc.urls')),
    path('admin/', admin.site.urls),
]

pmvc/models.py
from django.db import models

class Account(models.Model):
    name = models.CharField(max_length=30)
    enabled = models.BooleanField(default=True)

    def __str__(self):
        return self.name


def account_video_media_directory_path(instance, filename):
    print (instance)
    print (filename)
    return '{0}/{1}/{2}'.format(instance.account.id, instance.id, instance.title)


class Video(models.Model):
    title = models.CharField(max_length=30)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField()

    digital_master = models.FileField(upload_to=account_video_media_directory_path, blank=True, null=True)

    def __str__(self):
        return self.title

class Rendition(models.Model):
    name = models.CharField(max_length=20)
    url = models.URLField()
    video = models.ForeignKey(Video, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

pmvc/forms.py
from django import forms


class VideoCreateForm(forms.Form):
    title = forms.CharField(max_length=50)
    description = forms.CharField(max_length=500)
    digital_master = forms.FileField()

pmvc/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from .models import Account, Video
from .forms import VideoCreateForm
# from .tasks import handle_ingest_video
import boto3
import shastarain.settings as settings

def index(request):
    # log.debug("In the index view")

    accounts = Account.objects.all()
    response = render(request, 'pmvc/select_account.html', {'accounts': accounts})
    response.delete_cookie('pmvc_account_id')
    return response


def AccountHome(request):
    if 'pmvc_account_id' in request.COOKIES:
        account = Account.objects.get(account_id=request.COOKIES['pmvc_account_id'])
        return render(request, 'pmvc/account_selected.html', {'account': account})
    else:
        accounts = Account.objects.all()
        return render(request, 'pmvc/select_account.html', {'accounts': accounts})


def AccountSelectionHandler(request):
    selection = request.POST.get('acct_select')
    if selection == '0':
        # log.debug("Create New Company")
        # form = NewCompanyForm()
        # return render(request, 'setools/create_company_form.html', {'form': form})
        return redirect('pmvc:index')
    else:
        # log.debug("Company " + selection + " selected.")
        return redirect('pmvc:AccountSelected', selection)

def AccountSelected(request, account_id):
    account = Account.objects.get(id=account_id)
    response = render(request, 'pmvc/account_selected.html', {'account': account})
    response.set_cookie('pmvc_account_id', account_id)
    return response


def ListVideos(request, account_id):
    account = Account.objects.get(id=account_id)
    vids = Video.objects.filter(account=account)
    return render(request, 'pmvc/list_videos.html', {'vid_list': vids})

# def IngestVideo(request, account_id):
#     account = Account.objects.get(id=account_id)
#     return render(request, 'pmvc/ingest_video.html', {'account': account})

def handle_ingest_video(video_id, dm):
    video = Video.objects.get(pk=video_id)
    # Need to check the file extension - assuming mp4 for now.
    filename = 'videos/' + video.title + '/digital_master.mp4'
    # file = request.FILES['upload']
    s3 = boto3.resource('s3', aws_access_key_id=settings.AWS_ACCESS_KEY,
                        aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY)
    bucket = s3.Bucket(settings.AWS_VIDEO_BUCKET)
    bucket.put_object(Key=filename, Body=dm)

def IngestVideo(request, account_id):
    if request.method == 'POST':
        form = VideoCreateForm(request.POST, request.FILES)
        if form.is_valid():
            account = Account.objects.get(id=account_id)
            # instance = Video(file_field=request.FILES['file'])
            instance = Video(title=request.POST['title'], description=request.POST['description'], account=account)
            instance.save()
            # print (request.FILES['digital_master'].path)
            handle_ingest_video(instance.id, request.FILES['digital_master'])
            return HttpResponseRedirect('/success/url/')
    else:
        form = VideoCreateForm()
    return render(request, 'pmvc/upload_request.html', {'form': form})

templates/pmvc/account_selected.html
{% extends "pmvc/base_generic.html" %}

{% block content %}
    <h1>You are currently working on the company <strong>{{ account.name }}</strong></h1>
    <br>
    <p>
    Choose from the operations below:
    </p>
    <ul class="sidebar-nav">
          <li><a href="{% url 'pmvc:ListVideos' account.id %}">List Videos</a></li>
          <li><a href="{% url 'pmvc:IngestVideo' account.id%}">Ingest Video</a></li>
    </ul>
{% endblock %}

templates/pmvc/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Poor Mans Video Cloud!</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'se_tools/css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

</head>
<body>
<div class="jumbotron">
  <h1>Poor Mans Video Cloud</h1>
  <p>Welcome to the Poor Mans Video Cloud</p>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'pmvc:index' %}">Home</a></li>
                    <li><a href="{% url 'pmvc:AccountHome' %}">Company Home</a></li>
                </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
</div>
</body>
</html>

templates/pmvc/ingest_video.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/pmvc/list_videos.html
{% extends "pmvc/base_generic.html" %}

{% block content %}
    <div class="container">


  <p>Your Account has the following videos:</p>

     <table class="table table-bordered">
    <thead>
      <tr>
        <th>Video ID</th>
        <th>Title</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
    {% for vid in vid_list %}
      <tr>
        <td>{{ vid.id }}</td>
        <td>{{ vid.title }}</td>
        <td>{{ vid.description }}</td>
      </tr>
    {%  endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/pmvc/select_account.html
{% extends "pmvc/base_generic.html" %}

{% block content %}
    <p>Please select or create an account to work on:</p>

    <div class="container">
        <div class="row">
            <form action="{% url 'pmvc:AccountSelectionHandler' %}" method="post">
                {% csrf_token %}
                <div style="display: flex;">
                    <div class="col-sm-12">
                        <select class="form-control", id="acct_select" name="acct_select">
                            <option value="0">Create New Account</option>
                            <option disabled>──────────</option>
                            {% for account in accounts %}
                                <option value="{{ account.id }}">{{ account.name }}</option>
                            {% endfor %}

                        </select>
                    </div>
                    <div class="col-sm-8">
                        <!-- optional spacer: <div style="width: 8px;" /> -->
                        <button type="submit" class="btn btn-success">Go</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/pmvc/upload_request.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>